### ISSUE TITLE
make validate error: ModuleNotFoundError

### ISSUE THREAD

**Issue by Amine-OMRI** [engie-group/shaystack#15]
**Describe the bug**
When running make validate wich will automativcally run make-test wich will raise the follonwing error when testing the provider db : `ModuleNotFoundError: No module named 'supersqlite.third_party.internal.apsw'`

**To Reproduce**
1. git clone -b develop https://github.com/engie-group/shaystack.git
2. cd shaystack/
3. make configure
4. conda activate shaystack
5. make validate

**Used environment**
- conda 4.13.0
- ubuntu 22.04 and same error on 18.04
- GNU Make 4.3

**Error traceback**
```
ERROR: tests.test_provider_db.test_update_grid_in_db(<function _test_update_grid_in_db at 0x7f7cd1018820>, 'shaystack.providers.sql', 'sqlite3:///test.db#haystack', 0)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/shaystack/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/ubuntu/shaystack/tests/test_provider_db.py", line 43, in _wrapper
    function(provider, db)
  File "/home/ubuntu/shaystack/tests/test_provider_db.py", line 104, in _test_update_grid_in_db
    with cast(DBHaystackInterface, get_provider(provider_name,
  File "/home/ubuntu/shaystack/shaystack/providers/haystack_interface.py", line 542, in get_provider
    _providers[class_str] = FullInterface(envs)
  File "/home/ubuntu/shaystack/shaystack/providers/haystack_interface.py", line 459, in __init__
    provider_class.__init__(self, envs)
  File "/home/ubuntu/shaystack/shaystack/providers/sql.py", line 133, in __init__
    _import_db_driver(self._parsed_db,
  File "/home/ubuntu/shaystack/shaystack/providers/sql.py", line 84, in _import_db_driver
    mod = importlib.import_module(splitted[0])
  File "/home/ubuntu/anaconda3/envs/shaystack/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/envs/shaystack/lib/python3.8/site-packages/supersqlite/__init__.py", line 47, in <module>
    import supersqlite.third_party.internal.apsw as apsw
ModuleNotFoundError: No module named 'supersqlite.third_party.internal.apsw'
```

**Comment by Amine-OMRI** [comment]
- Can't build `supersqlite` which is a SQLite library for Python with the latest commit dated 2019 and the latest realse dated 2018. 

- Should find another alternative for manipulating SQLite database like `sqlite-utils`, `peewee` or `apsw` but it should support shaystack providers implementation
